{
 "title": "Ambientale",
 "description": "Dashboard per la visualizzazione di varie tipologie di sensori ambientali dislocati in una città",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Mappa Sensori",
   "type": "geomap",
   "description": "dislocazione geografica dei sensori ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name,\n       'temperature' as Tipo,\n       argMax(latitude,timestamp) as latitude,\n       argMax(longitude,timestamp) as longitude\nFROM innovacity.temperatures\nGROUP BY name\nHAVING ( timestamp  >= $__fromTime AND timestamp <= $__toTime );"
    },
    {
     "rawSql": "SELECT name,\n       'rain' as Tipo,\n       argMax(latitude,timestamp) as latitude,\n       argMax(longitude,timestamp) as longitude\nFROM innovacity.rain\nGROUP BY name\nHAVING ( timestamp  >= $__fromTime AND timestamp <= $__toTime );"
    },
    {
     "rawSql": "SELECT name,\n       'reservoir' as Tipo,\n       argMax(latitude,timestamp) as latitude,\n       argMax(longitude,timestamp) as longitude\nFROM innovacity.reservoirs\nGROUP BY name\nHAVING ( timestamp  >= $__fromTime AND timestamp <= $__toTime );"
    },
    {
     "rawSql": "SELECT name,\n       'wind' as Tipo,\n       argMax(latitude,timestamp) as latitude,\n       argMax(longitude,timestamp) as longitude\nFROM innovacity.wind\nGROUP BY name\nHAVING ( timestamp  >= $__fromTime AND timestamp <= $__toTime );"
    },
    {
     "rawSql": "SELECT name,\n       'humidity' as Tipo,\n       argMax(latitude,timestamp) as latitude,\n       argMax(longitude,timestamp) as longitude\nFROM innovacity.humidity\nGROUP BY name\nHAVING ( timestamp  >= $__fromTime AND timestamp <= $__toTime );"
    }
   ]
  },
  {
   "title": "Temperatura media per minuto",
   "type": "timeseries",
   "description": "calcola la temperatura media ogni minuto ",
   "gridPos": { "h": 9, "w": 15, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    name,\r\n    toStartOfMinute(timestamp1m) AS timestamp1m,\r\n    avgMerge(avgTemperature) as \" \"\r\nFROM innovacity.temperatures1m\r\nGROUP BY (name, timestamp1m)\r\nHAVING ( timestamp1m  >= $__fromTime AND timestamp1m <= $__toTime ) ",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT\n    timestamp5m,\n    avgTemperature\nFROM innovacity.temperatures5m_overall\nWHERE (timestamp5m, insertion_timestamp) IN (\n    SELECT\n        timestamp5m,\n        max(insertion_timestamp) AS max_insertion_timestamp\n    FROM innovacity.temperatures5m_overall\n    GROUP BY timestamp5m\n);\n"
    }
   ]
  },
  {
   "title": "Temperatura media ",
   "type": "stat",
   "description": "temperatura media nell'intervallo temporale selezionato",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avgMerge(avgTemperature) as avgTemperature\nFROM innovacity.temperatures1m\nWHERE (timestamp1m >= $__fromTime AND timestamp1m <= $__toTime);",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Pioggia media per minuto",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 2, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp1m,\n  AVG(moving_average) AS media_totale\nFROM (\n  SELECT\n    avgMerge(avgRain) OVER (ORDER BY timestamp1m ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as moving_average,\n    timestamp1m\n  FROM innovacity.rain1m\n) AS subquery\nGROUP BY timestamp1m\nORDER BY timestamp1m;\n\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Intensità media pioggia",
   "type": "gauge",
   "description": "Intensità media della pioggia in base all'intervallo selezionato ",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avgMerge(avgRain) as avgRain\nFROM innovacity.rain1m\nWHERE (timestamp1m >= $__fromTime AND timestamp1m <= $__toTime);",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Riempimento medio dei bacini idrici per minuto",
   "type": "timeseries",
   "description": "calcola il riempimento medio dei bacini idrici ogni minuto",
   "gridPos": { "h": 9, "w": 20, "x": 2, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    name,\r\n    toStartOfMinute(timestamp1m) AS timestamp1m,\r\n    avgMerge(avgReservoir) as avgReservoir\r\nFROM innovacity.reservoirs1m\r\nGROUP BY (name, timestamp1m)\r\nHAVING ( timestamp1m  >= $__fromTime AND timestamp1m <= $__toTime ) ",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT\n  timestamp1m,\n  AVG(moving_average) AS moving_average\nFROM (\n  SELECT\n    avgMerge(avgReservoir) OVER (ORDER BY timestamp1m ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as moving_average,\n    timestamp1m\n  FROM innovacity.reservoirs1m\n) AS subquery\nGROUP BY timestamp1m\nORDER BY timestamp1m;"
    }
   ]
  },
  {
   "title": "Qualità dell'aria",
   "type": "timeseries",
   "description": "Misura PM10",
   "gridPos": { "h": 9, "w": 20, "x": 2, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n    name,\n    toStartOfMinute(timestamp1m) AS timestamp1m,\n    avgMerge(avg_air_pollution) as avg_air_pollution\nFROM innovacity.air_pollution1m\nGROUP BY (name, timestamp1m)\nHAVING ( timestamp1m  >= $__fromTime AND timestamp1m <= $__toTime ) "
    },
    {
     "rawSql": "SELECT\n  timestamp1m,\n  AVG(moving_average) AS moving_average\nFROM (\n  SELECT\n    avgMerge(avg_air_pollution) OVER (ORDER BY timestamp1m ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as moving_average,\n    timestamp1m\n  FROM innovacity.air_pollution1m\n) AS subquery\nGROUP BY timestamp1m\nORDER BY timestamp1m;"
    }
   ]
  },
  {
   "title": "Umidità relativa per minuto",
   "type": "timeseries",
   "description": "Misura la percentuale di umidità relativa presente nell'aria",
   "gridPos": { "h": 8, "w": 20, "x": 2, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT\n    name,\n    toStartOfMinute(timestamp1m) AS timestamp1m,\n    avgMerge(avgHumidity) as avgHumidity\nFROM innovacity.humidity1m\nGROUP BY (name, timestamp1m)\nHAVING ( timestamp1m  >= $__fromTime AND timestamp1m <= $__toTime ) "
    },
    {
     "rawSql": "SELECT\n  timestamp1m,\n  AVG(moving_average) AS moving_average\nFROM (\n  SELECT\n    avgMerge(avgHumidity) OVER (ORDER BY timestamp1m ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as moving_average,\n    timestamp1m\n  FROM innovacity.humidity1m\n) AS subquery\nGROUP BY timestamp1m\nORDER BY timestamp1m;"
    }
   ]
  },
  {
   "title": "Vento",
   "type": "geomap",
   "description": "Pannello mostrante la direzione e intensità del vento.",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "rawSql": "SELECT name,\n       argMax(value, timestamp) AS value,\n       argMax(type, timestamp) as type,\n       argMax(direction, timestamp) as direction,\n       argMax(latitude,timestamp) as latitude,\n       argMax(longitude,timestamp) as longitude\nFROM innovacity.wind\nGROUP BY name;"
    }
   ]
  },
  {
   "title": "Vento (dati)",
   "type": "table",
   "description": "Tabella mostrante i dati grezzi relativi al vento.",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 54 },
   "targets": [
    { "panelId": 14 }
   ]
  }
 ]
}