{
 "title": "Urbanistica",
 "description": "pannelli urbanistici ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disponibilità Parcheggi",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT name,\n       argMax(current,timestamp) as current,\n       argMax(max_slots,timestamp) as max_slots,\n       argMax(latitude,timestamp) as latitude,\n       argMax(longitude,timestamp) as longitude\nFROM innovacity.parking\nGROUP BY name\nHAVING ( timestamp  >= $__fromTime AND timestamp <= $__toTime );"
    }
   ]
  },
  {
   "title": "Mappa: Biciclette elettriche e percentuale batteria",
   "type": "geomap",
   "description": "Visualizzazione percentuale batteria delle biciclette elettriche",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT name,\r\n       argMax(value,timestamp) as value,\r\n       argMax(latitude,timestamp) as latitude,\r\n       argMax(longitude,timestamp) as longitude\r\nFROM innovacity.ebikes\r\nGROUP BY name\r\nHAVING ( timestamp  >= $__fromTime AND timestamp <= $__toTime );"
    }
   ]
  },
  {
   "title": "Mappa: posizione isole ecologiche e riempimento",
   "type": "geomap",
   "description": "Visualizzazione riempimento isole ecologiche",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT name,\n       argMax(value,timestamp) as value,\n       argMax(latitude,timestamp) as latitude,\n       argMax(longitude,timestamp) as longitude\nFROM innovacity.eco_zone\nGROUP BY name\nHAVING ( timestamp  >= $__fromTime AND timestamp <= $__toTime );"
    }
   ]
  },
  {
   "title": "Traffico",
   "type": "geomap",
   "description": "Visualizza il livello di traffico e il numero di macchine sulle diverse strade",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  name, \n  argMax(name, timestamp),\n  argMax(timestamp, timestamp),\n  argMax(latitude, timestamp),\n  argMax(longitude, timestamp),\n  argMax(num_cars, timestamp),\n  argMax(avg_time, timestamp),\n  argMax(traffic_level, timestamp)\nFROM innovacity.traffic\nGROUP BY name"
    }
   ]
  },
  {
   "title": "Mappa Stazioni di Ricarica",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n    name as Name, \n    argMax(erogation_power, timestamp) AS \"PowerErogation\",\n    argMax(availability, timestamp) AS Availability,\n    argMax(latitude, timestamp) AS Latitude,\n    argMax(longitude, timestamp) AS Longitude\nFROM\n    innovacity.charging_station\nGROUP BY\n    name;"
    }
   ]
  },
  {
   "title": "Erogazione Stazioni di RIcarica",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "targets": [
    { "panelId": 3 }
   ]
  }
 ]
}