{
 "title": "Superamento soglie",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Superamento soglia precipitazioni (50mm/m^2)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    name,\n    toStartOfMinute(timestamp1m) AS timestamp1m,\n    avgMerge(avgRain) as value\nFROM\n    innovacity.rain1m\nGROUP BY (name, timestamp1m)\nHAVING \n    (timestamp1m >= $__fromTime AND timestamp1m <= $__toTime) \n    AND (value > 50)\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "Superamento soglia riempimento zone ecologiche (80%)",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n    name,\n    timestamp,\n    value\nFROM\n    innovacity.eco_zone\nWHERE\n    value > 80\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "Superamento soglie livello bacini idrici (70%)",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n    name,\n    toStartOfMinute(timestamp1m) AS timestamp1m,\n    avgMerge(avgReservoir) as value\nFROM innovacity.reservoirs1m\nGROUP BY (name, timestamp1m)\nHAVING \n    (timestamp1m >= $__fromTime AND timestamp1m <= $__toTime) \n    AND (value > 70)\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "Superamento soglia inquinamento dell'aria (80μg/m^3)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n    name,\n    toStartOfMinute(timestamp1m) AS timestamp1m,\n    avgMerge(avg_air_pollution) as value\nFROM innovacity.air_pollution1m\nGROUP BY (name, timestamp1m)\nHAVING \n    (timestamp1m >= $__fromTime AND timestamp1m <= $__toTime) \n    AND (value > 80)\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "Superamento soglia temperatura (40°)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n    name,\n    toStartOfMinute(timestamp1m) AS timestamp1m,\n    avgMerge(avgTemperature) as value\nFROM innovacity.temperatures1m\nGROUP BY (name, timestamp1m)\nHAVING \n    (timestamp1m >= $__fromTime AND timestamp1m <= $__toTime) \n    AND (value > 40)\nORDER BY value DESC;"
    }
   ]
  }
 ]
}