{
 "title": "Temperature",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \"value\", \"uuid\", \"timestamp\" FROM \"innovacity\".\"temperatures\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperatures Avg By 5 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n    uuid,\n    toStartOfFiveMinutes(timestamp5m) AS timestamp5m,\n    avgMerge(avgTemperature) as avgTemperature\nFROM innovacity.temperatures5m\nGROUP BY (uuid, timestamp5m)\nHAVING ( timestamp5m  >= $__fromTime AND timestamp5m <= $__toTime ) ",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Readings per Table per Query",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) count FROM \"innovacity\".\"temperatures\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT count(*) count FROM \"innovacity\".\"temperatures5m\" WHERE   ( timestamp5m  >= $__fromTime AND timestamp5m <= $__toTime )"
    }
   ]
  }
 ]
}