name: Development
run-name: Syntax
on: ["push"]
jobs:
    formatting:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - name: autopep8
            uses: peter-evans/autopep8@v2
            with:
              args: --recursive --in-place --aggressive --aggressive .